### ISSUE TITLE
Incompatible with Error Handler and Debugger

### ISSUE THREAD

**Issue by IsoKilo** [cvghivebrain/axm68k#6]
Upon building with [Vladikcomper's Error Handler and Debugger (Version 2.0)](https://sonicresearch.org/community/index.php?threads/advanced-error-handler-and-debugger.4442/#post-78456), AXM68k runs into issues with it's formatting not faced with ASM68k.
Last commit in which the debugger was compatible was the [commit on October 29, 2022.](https://github.com/cvghivebrain/axm68k/tree/9eff6d90e289e9a4c962b367a41e186bf983ea66)

Errors:
```
ERRORHANDLER.ASM(34) : Error : Expecting comma between operands in 'instr'
num: equ instr('BUS ERROR'

ERRORHANDLER.ASM(34) : Error : Missing ')' after function parameter(s)
elseif instr('a b c d e h l (hl) ', ' '%<') ')

ERRORHANDLER.ASM(34) : Error : Expected comma between operands
if strcmp(' '%<')', 'a')

ERRORHANDLER.ASM(34) : Fatal error :  Use = instead of SET for redefinable symbols.
```

While this is only one tool affected, other macro heavy utilities converting from ASM68k to AXM may face similar issues.

**Comment by cvghivebrain** [comment]
SET is a Z80 instruction, so you can't use it as you would in ASM68k. Try replacing all instances of SET with = and see if that fixes it.

**Comment by IsoKilo** [comment]
Sure enough. I may as well write up the step by step for others who encounter this issue.
The line the assembler is failing at is;
```
	__ErrorMessage "BUS ERROR", _eh_default|_eh_address_error
```
But notice how 'set' isn't even used here? It's because it's a macro from Debugger.asm. So we need to open that file. 'set' is used at the following lines: 170, 171, 172, 178, 179, 212, 227, 228, 237, 238, 264, 265. And as Hivebrain said, simply change 'set' to =.
You also should change the equate 'dec' to 'deci' since dec is also a Z80 instruction.
Happy debugging!
