### ISSUE TITLE
Can't Globally Reference Local Label with @ Symbol

### ISSUE THREAD

**Issue by Pr0jectFM** [cvghivebrain/axm68k#8]
When the local label symbol is ".", then you can globally reference a local label like this:
`Global.local`
However, when the local label symbol is "@", then doing
`Global@local`
results in an error.

**Comment by cvghivebrain** [comment]
As far as I know, you can only use local labels like that with AS, not with asm68k. In any case, axm68k is just a set of macros. There's no way for me to change how labels work at a base level.

**Comment by Pr0jectFM** [comment]
Yeah, you're right. I thought it was working when I tried it, but trying it again, it really doesn't.
